


on:
  push:
    branches: [ master ]
    
  workflow_dispatch:


jobs:
  build-and-test-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8 so that I can run Java
        uses: actions/setup-java@v1
        with:
          - java-version: 1.8

      - name: Build with Gradle!
        working-directory: .
        run: ./gradlew build -x test

      - name: Run tests, please!
        working-directory: .
        run: ./gradlew test
